### ISSUE TITLE
User’s Name Page HTML

### ISSUE THREAD

**Issue by clairesersun** [clairesersun/com6338-10-10-avillanoza-rossello-sersun#1]
Acceptance Criteria: 
- New page 
- Include logo at top of page 
- Create a form that asks for the user’s name 
- The forms label asks for their name

**Comment by carolina-ross** [comment]
This is done and updated

**Comment by carolina-ross** [comment]
This is done and updated

**Comment by carolina-ross** [comment]
Update Index.html for JS
