### ISSUE TITLE
Pull Page HTML

### ISSUE THREAD

**Issue by clairesersun** [clairesersun/com6338-10-10-avillanoza-rossello-sersun#16]
Acceptance Criteria: 
- In header: LOGO, home btn, refresh img 
- Top section includes “pull”, “: breakdown / summary”, and red linear design 
- Scrolling list of pull exercises pulled from Workout API (empty textNode)

**Comment by carolina-ross** [comment]
HTML file created by Carolina and modified/updated by Jonah
The initial HTML file was uploaded before the issue was created.
