### ISSUE TITLE
 General Mobile Stylings 

### ISSUE THREAD

**Issue by clairesersun** [clairesersun/com6338-10-10-avillanoza-rossello-sersun#19]
Acceptance Criteria: 
- On top of style sheet have root styles 
- Create general styling for elements and blocks

**Comment by avillajd** [comment]
claire & carolina, 

1. Please take a look at the changes i made to the .html files. 
2. I added the logo to all the pages. 
3. I made a Stylesheet.css file.
4. Still not sure about a couple of the choices made so if you hate them ie: removing buttons in the nav, got rid of the subdivision form actions from the workouts page you can just take em out. 
5. I tried to change the file names to be lowercase with no space but it was getting super buggy. 

Please comment below and fix anything you see as an issue i haven't seen. 

For the CSS section for instance... I have to go back and watch efren's video from last semester... my brain is just mush right now. If you see easy DUH! fixes please let me know. 

-J
